# -*- coding: utf-8 -*-
"""analysis_restaurant.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M_Lpgq2LDSqCCkQs9Cp6AfyUJLLPK3oP
"""

import seaborn as sns
import pandas as pd

tips = sns.load_dataset('tips')

tips.head() #show first rows

#tips.day.unique() #days of data

tips.time.unique() #times of data

tips.tail() # last rows

tips.time.value_counts().plot(kind='bar') # plot how many time data for each category

tips.time.value_counts(normalize = True) # % of dinner and lunch

tips.groupby(['time'])['tip'].mean()
# group by time, mean of tips - which time has bigger tips

sex = tips.groupby(['sex'])['tip'].mean()
smoker = tips.groupby(['smoker'])['tip'].mean()

print(sex)
print('')
print(smoker)

#cross table for smoker and tips
tips.groupby(['smoker', 'sex'])['tip'].mean() #groupby with two dimensions

#use of unstack for more clean data
tips.groupby(['smoker', 'sex'])['tip'].mean().unstack()

tips['tip_pct'] = tips.tip / tips.total_bill #create new column with % tips to total bill

tips.head() #check new column

# visualize relation between total bill and tip
tips.plot.scatter(x = 'total_bill', y = 'tip')

sns.scatterplot(x = 'total_bill', y = 'tip', data = tips)

sns.scatterplot(x = 'total_bill', y = 'tip', data = tips, hue = 'sex') # color by sex
# sns.scatterplot(x = 'total_bill', y = 'tip', data = tips, hue = 'time') # color by time

#bifurcation of time based on sex
sns.relplot(x = 'total_bill', y = 'tip', data = tips, col = 'sex', hue = 'time')

#distribution of total bill by time
sns.displot(x = 'total_bill', data = tips, col = 'time', kde = True)

#distribution of tip by time
sns.displot(x = 'tip', data = tips, col = 'time', kde = True)

sns.pairplot(data = tips, hue = 'sex')